### ISSUE TITLE
Exception: “write while request pending”

### ISSUE THREAD

**Issue by mariusae** [twitter/finagle#195]
Reported by @rstrickland, with the following stack trace:

	2013-08-19 07:55:14,025 ERROR c.w.d.d.FourInfoActor [New I/O  worker #22] <* DC [Failed] : java.lang.Exception: write while request pending (Chan=sms, Prod=severe, Addresses=List(6786707884))
	com.twitter.finagle.WriteException$$anon$1: java.lang.Exception: write while request pending
		at com.twitter.finagle.transport.ClientChannelTransport$$anonfun$2.apply(ChannelTransport.scala:99) ~[Distribution-Server-1.1.4-RELEASE-jar-with-dependencies.jar:?]
		at com.twitter.finagle.transport.ClientChannelTransport$$anonfun$2.apply(ChannelTransport.scala:96) ~[Distribution-Server-1.1.4-RELEASE-jar-with-dependencies.jar:?]
		at com.twitter.finagle.util.Proc$class.$bang(Chan.scala:34) ~[Distribution-Server-1.1.4-RELEASE-jar-with-dependencies.jar:?]
		at com.twitter.finagle.util.Proc$$anon$1.$bang(Chan.scala:47) ~[Distribution-Server-1.1.4-RELEASE-jar-with-dependencies.jar:?]
		at com.twitter.finagle.transport.ClientChannelTransport.write(ChannelTransport.scala:146) ~[Distribution-Server-1.1.4-RELEASE-jar-with-dependencies.jar:?]
		at com.twitter.finagle.dispatch.SerialClientDispatcher.dispatch(ClientDispatcher.scala:37) ~[Distribution-Server-1.1.4-RELEASE-jar-with-dependencies.jar:?]
		at com.twitter.finagle.dispatch.SerialClientDispatcher$$anonfun$apply$2.apply(ClientDispatcher.scala:50) ~[Distribution-Server-1.1.4-RELEASE-jar-with-dependencies.jar:?]
		at com.twitter.finagle.dispatch.SerialClientDispatcher$$anonfun$apply$2.apply(ClientDispatcher.scala:49) ~[Distribution-Server-1.1.4-RELEASE-jar-with-dependencies.jar:?]
		at com.twitter.util.Future$$anonfun$onSuccess$1.apply(Future.scala:645) ~[Distribution-Server-1.1.4-RELEASE-jar-with-dependencies.jar:?]
		at com.twitter.util.Future$$anonfun$onSuccess$1.apply(Future.scala:644) ~[Distribution-Server-1.1.4-RELEASE-jar-with-dependencies.jar:?]
		at com.twitter.util.Promise$Monitored.apply(Promise.scala:40) ~[Distribution-Server-1.1.4-RELEASE-jar-with-dependencies.jar:?]
		at com.twitter.util.Promise$Monitored.apply(Promise.scala:31) ~[Distribution-Server-1.1.4-RELEASE-jar-with-dependencies.jar:?]
		at com.twitter.util.Promise$$anon$2.run(Promise.scala:519) ~[Distribution-Server-1.1.4-RELEASE-jar-with-dependencies.jar:?]
		at com.twitter.concurrent.Scheduler$LocalScheduler.run(Scheduler.scala:60) [Distribution-Server-1.1.4-RELEASE-jar-with-dependencies.jar:?]
		at com.twitter.concurrent.Scheduler$LocalScheduler.submit(Scheduler.scala:40) [Distribution-Server-1.1.4-RELEASE-jar-with-dependencies.jar:?]
		at com.twitter.concurrent.Scheduler$.submit(Scheduler.scala:26) [Distribution-Server-1.1.4-RELEASE-jar-with-dependencies.jar:?]
		at com.twitter.util.Promise.runq(Promise.scala:248) [Distribution-Server-1.1.4-RELEASE-jar-with-dependencies.jar:?]
		at com.twitter.util.Promise.updateIfEmpty(Promise.scala:492) [Distribution-Server-1.1.4-RELEASE-jar-with-dependencies.jar:?]
		at com.twitter.util.Promise.update(Promise.scala:475) [Distribution-Server-1.1.4-RELEASE-jar-with-dependencies.jar:?]
		at com.twitter.finagle.channel.ConnectionLifecycleHandler$$anonfun$com$twitter$finagle$channel$ConnectionLifecycleHandler$$channelDidConnect$1.apply$mcV$sp(ConnectionLifecycleHandler.scala:19) [Distribution-Server-1.1.4-RELEASE-jar-with-dependencies.jar:?]
		at com.twitter.finagle.netty3.RichChannelFuture$$anonfun$onSuccessOrFailure$1.apply(ChannelFuture.scala:126) [Distribution-Server-1.1.4-RELEASE-jar-with-dependencies.jar:?]
		at com.twitter.finagle.netty3.RichChannelFuture$$anonfun$onSuccessOrFailure$1.apply(ChannelFuture.scala:124) [Distribution-Server-1.1.4-RELEASE-jar-with-dependencies.jar:?]
		at com.twitter.finagle.netty3.RichChannelFuture$$anon$1.operationComplete(ChannelFuture.scala:28) [Distribution-Server-1.1.4-RELEASE-jar-with-dependencies.jar:?]
		at org.jboss.netty.channel.DefaultChannelFuture.notifyListener(DefaultChannelFuture.java:428) [Distribution-Server-1.1.4-RELEASE-jar-with-dependencies.jar:?]
		at org.jboss.netty.channel.DefaultChannelFuture.notifyListeners(DefaultChannelFuture.java:414) [Distribution-Server-1.1.4-RELEASE-jar-with-dependencies.jar:?]
		at org.jboss.netty.channel.DefaultChannelFuture.setSuccess(DefaultChannelFuture.java:363) [Distribution-Server-1.1.4-RELEASE-jar-with-dependencies.jar:?]
		at org.jboss.netty.channel.AbstractChannel$ChannelCloseFuture.setClosed(AbstractChannel.java:355) [Distribution-Server-1.1.4-RELEASE-jar-with-dependencies.jar:?]
		at org.jboss.netty.channel.AbstractChannel.setClosed(AbstractChannel.java:185) [Distribution-Server-1.1.4-RELEASE-jar-with-dependencies.jar:?]
		at org.jboss.netty.channel.socket.nio.AbstractNioChannel.setClosed(AbstractNioChannel.java:204) [Distribution-Server-1.1.4-RELEASE-jar-with-dependencies.jar:?]
		at org.jboss.netty.channel.socket.nio.NioSocketChannel.setClosed(NioSocketChannel.java:85) [Distribution-Server-1.1.4-RELEASE-jar-with-dependencies.jar:?]
		at org.jboss.netty.channel.socket.nio.AbstractNioWorker.close(AbstractNioWorker.java:717) [Distribution-Server-1.1.4-RELEASE-jar-with-dependencies.jar:?]
		at org.jboss.netty.channel.socket.nio.NioClientSocketPipelineSink.eventSunk(NioClientSocketPipelineSink.java:99) [Distribution-Server-1.1.4-RELEASE-jar-with-dependencies.jar:?]
		at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendDownstream(DefaultChannelPipeline.java:774) [Distribution-Server-1.1.4-RELEASE-jar-with-dependencies.jar:?]
		at org.jboss.netty.channel.SimpleChannelHandler.closeRequested(SimpleChannelHandler.java:338) [Distribution-Server-1.1.4-RELEASE-jar-with-dependencies.jar:?]
		at org.jboss.netty.channel.SimpleChannelHandler.handleDownstream(SimpleChannelHandler.java:260) [Distribution-Server-1.1.4-RELEASE-jar-with-dependencies.jar:?]
		at org.jboss.netty.channel.DefaultChannelPipeline.sendDownstream(DefaultChannelPipeline.java:585) [Distribution-Server-1.1.4-RELEASE-jar-with-dependencies.jar:?]
		at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendDownstream(DefaultChannelPipeline.java:779) [Distribution-Server-1.1.4-RELEASE-jar-with-dependencies.jar:?]
		at org.jboss.netty.channel.SimpleChannelHandler.closeRequested(SimpleChannelHandler.java:338) [Distribution-Server-1.1.4-RELEASE-jar-with-dependencies.jar:?]
		at com.twitter.finagle.channel.ChannelStatsHandler.closeRequested(ChannelStatsHandler.scala:83) [Distribution-Server-1.1.4-RELEASE-jar-with-dependencies.jar:?]
		at org.jboss.netty.channel.SimpleChannelHandler.handleDownstream(SimpleChannelHandler.java:260) [Distribution-Server-1.1.4-RELEASE-jar-with-dependencies.jar:?]
		at org.jboss.netty.channel.DefaultChannelPipeline.sendDownstream(DefaultChannelPipeline.java:585) [Distribution-Server-1.1.4-RELEASE-jar-with-dependencies.jar:?]
		at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendDownstream(DefaultChannelPipeline.java:779) [Distribution-Server-1.1.4-RELEASE-jar-with-dependencies.jar:?]
		at org.jboss.netty.handler.codec.oneone.OneToOneEncoder.handleDownstream(OneToOneEncoder.java:54) [Distribution-Server-1.1.4-RELEASE-jar-with-dependencies.jar:?]
		at org.jboss.netty.handler.codec.http.HttpClientCodec.handleDownstream(HttpClientCodec.java:97) [Distribution-Server-1.1.4-RELEASE-jar-with-dependencies.jar:?]
		at org.jboss.netty.channel.DefaultChannelPipeline.sendDownstream(DefaultChannelPipeline.java:585) [Distribution-Server-1.1.4-RELEASE-jar-with-dependencies.jar:?]
		at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendDownstream(DefaultChannelPipeline.java:779) [Distribution-Server-1.1.4-RELEASE-jar-with-dependencies.jar:?]
		at org.jboss.netty.channel.SimpleChannelDownstreamHandler.closeRequested(SimpleChannelDownstreamHandler.java:154) [Distribution-Server-1.1.4-RELEASE-jar-with-dependencies.jar:?]
		at org.jboss.netty.channel.SimpleChannelDownstreamHandler.handleDownstream(SimpleChannelDownstreamHandler.java:76) [Distribution-Server-1.1.4-RELEASE-jar-with-dependencies.jar:?]
		at org.jboss.netty.channel.DefaultChannelPipeline.sendDownstream(DefaultChannelPipeline.java:585) [Distribution-Server-1.1.4-RELEASE-jar-with-dependencies.jar:?]
		at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendDownstream(DefaultChannelPipeline.java:779) [Distribution-Server-1.1.4-RELEASE-jar-with-dependencies.jar:?]
		at org.jboss.netty.channel.SimpleChannelDownstreamHandler.closeRequested(SimpleChannelDownstreamHandler.java:154) [Distribution-Server-1.1.4-RELEASE-jar-with-dependencies.jar:?]
		at org.jboss.netty.channel.SimpleChannelDownstreamHandler.handleDownstream(SimpleChannelDownstreamHandler.java:76) [Distribution-Server-1.1.4-RELEASE-jar-with-dependencies.jar:?]
		at org.jboss.netty.channel.DefaultChannelPipeline.sendDownstream(DefaultChannelPipeline.java:585) [Distribution-Server-1.1.4-RELEASE-jar-with-dependencies.jar:?]
		at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendDownstream(DefaultChannelPipeline.java:779) [Distribution-Server-1.1.4-RELEASE-jar-with-dependencies.jar:?]
		at org.jboss.netty.channel.SimpleChannelHandler.closeRequested(SimpleChannelHandler.java:338) [Distribution-Server-1.1.4-RELEASE-jar-with-dependencies.jar:?]
		at org.jboss.netty.channel.SimpleChannelHandler.handleDownstream(SimpleChannelHandler.java:260) [Distribution-Server-1.1.4-RELEASE-jar-with-dependencies.jar:?]
		at org.jboss.netty.channel.DefaultChannelPipeline.sendDownstream(DefaultChannelPipeline.java:585) [Distribution-Server-1.1.4-RELEASE-jar-with-dependencies.jar:?]
		at org.jboss.netty.channel.DefaultChannelPipeline.sendDownstream(DefaultChannelPipeline.java:576) [Distribution-Server-1.1.4-RELEASE-jar-with-dependencies.jar:?]
		at org.jboss.netty.channel.Channels.close(Channels.java:820) [Distribution-Server-1.1.4-RELEASE-jar-with-dependencies.jar:?]
		at com.twitter.finagle.transport.ClientChannelTransport.close(ChannelTransport.scala:156) [Distribution-Server-1.1.4-RELEASE-jar-with-dependencies.jar:?]
		at com.twitter.util.Closable$class.close(Closable.scala:12) [Distribution-Server-1.1.4-RELEASE-jar-with-dependencies.jar:?]
		at com.twitter.finagle.transport.ClientChannelTransport.close(ChannelTransport.scala:88) [Distribution-Server-1.1.4-RELEASE-jar-with-dependencies.jar:?]
		at com.twitter.finagle.transport.ClientChannelTransport.fail(ChannelTransport.scala:115) [Distribution-Server-1.1.4-RELEASE-jar-with-dependencies.jar:?]
		at com.twitter.finagle.transport.ClientChannelTransport.handleUpstream(ChannelTransport.scala:135) [Distribution-Server-1.1.4-RELEASE-jar-with-dependencies.jar:?]
		at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:558) [Distribution-Server-1.1.4-RELEASE-jar-with-dependencies.jar:?]
		at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:786) [Distribution-Server-1.1.4-RELEASE-jar-with-dependencies.jar:?]
		at org.jboss.netty.channel.SimpleChannelHandler.exceptionCaught(SimpleChannelHandler.java:156) [Distribution-Server-1.1.4-RELEASE-jar-with-dependencies.jar:?]
		at org.jboss.netty.channel.SimpleChannelHandler.handleUpstream(SimpleChannelHandler.java:130) [Distribution-Server-1.1.4-RELEASE-jar-with-dependencies.jar:?]
		at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:558) [Distribution-Server-1.1.4-RELEASE-jar-with-dependencies.jar:?]
		at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:786) [Distribution-Server-1.1.4-RELEASE-jar-with-dependencies.jar:?]
		at org.jboss.netty.channel.SimpleChannelUpstreamHandler.exceptionCaught(SimpleChannelUpstreamHandler.java:153) [Distribution-Server-1.1.4-RELEASE-jar-with-dependencies.jar:?]
		at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:112) [Distribution-Server-1.1.4-RELEASE-jar-with-dependencies.jar:?]
		at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:558) [Distribution-Server-1.1.4-RELEASE-jar-with-dependencies.jar:?]
		at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:786) [Distribution-Server-1.1.4-RELEASE-jar-with-dependencies.jar:?]
		at org.jboss.netty.channel.SimpleChannelUpstreamHandler.exceptionCaught(SimpleChannelUpstreamHandler.java:153) [Distribution-Server-1.1.4-RELEASE-jar-with-dependencies.jar:?]
		at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:112) [Distribution-Server-1.1.4-RELEASE-jar-with-dependencies.jar:?]
		at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:558) [Distribution-Server-1.1.4-RELEASE-jar-with-dependencies.jar:?]
		at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:786) [Distribution-Server-1.1.4-RELEASE-jar-with-dependencies.jar:?]
		at org.jboss.netty.handler.codec.frame.FrameDecoder.exceptionCaught(FrameDecoder.java:378) [Distribution-Server-1.1.4-RELEASE-jar-with-dependencies.jar:?]
		at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:112) [Distribution-Server-1.1.4-RELEASE-jar-with-dependencies.jar:?]
		at org.jboss.netty.handler.codec.http.HttpClientCodec.handleUpstream(HttpClientCodec.java:92) [Distribution-Server-1.1.4-RELEASE-jar-with-dependencies.jar:?]
		at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:558) [Distribution-Server-1.1.4-RELEASE-jar-with-dependencies.jar:?]
		at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:786) [Distribution-Server-1.1.4-RELEASE-jar-with-dependencies.jar:?]
		at org.jboss.netty.channel.SimpleChannelHandler.exceptionCaught(SimpleChannelHandler.java:156) [Distribution-Server-1.1.4-RELEASE-jar-with-dependencies.jar:?]
		at com.twitter.finagle.channel.ChannelStatsHandler.exceptionCaught(ChannelStatsHandler.scala:94) [Distribution-Server-1.1.4-RELEASE-jar-with-dependencies.jar:?]
		at org.jboss.netty.channel.SimpleChannelHandler.handleUpstream(SimpleChannelHandler.java:130) [Distribution-Server-1.1.4-RELEASE-jar-with-dependencies.jar:?]
		at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:558) [Distribution-Server-1.1.4-RELEASE-jar-with-dependencies.jar:?]
		at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:786) [Distribution-Server-1.1.4-RELEASE-jar-with-dependencies.jar:?]
		at org.jboss.netty.channel.SimpleChannelHandler.exceptionCaught(SimpleChannelHandler.java:156) [Distribution-Server-1.1.4-RELEASE-jar-with-dependencies.jar:?]
		at org.jboss.netty.channel.SimpleChannelHandler.handleUpstream(SimpleChannelHandler.java:130) [Distribution-Server-1.1.4-RELEASE-jar-with-dependencies.jar:?]
		at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:558) [Distribution-Server-1.1.4-RELEASE-jar-with-dependencies.jar:?]
		at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:553) [Distribution-Server-1.1.4-RELEASE-jar-with-dependencies.jar:?]
		at org.jboss.netty.channel.Channels.fireExceptionCaught(Channels.java:533) [Distribution-Server-1.1.4-RELEASE-jar-with-dependencies.jar:?]
		at org.jboss.netty.channel.AbstractChannelSink.exceptionCaught(AbstractChannelSink.java:48) [Distribution-Server-1.1.4-RELEASE-jar-with-dependencies.jar:?]
		at org.jboss.netty.channel.DefaultChannelPipeline.notifyHandlerException(DefaultChannelPipeline.java:652) [Distribution-Server-1.1.4-RELEASE-jar-with-dependencies.jar:?]
		at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:560) [Distribution-Server-1.1.4-RELEASE-jar-with-dependencies.jar:?]
		at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:786) [Distribution-Server-1.1.4-RELEASE-jar-with-dependencies.jar:?]
		at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:281) [Distribution-Server-1.1.4-RELEASE-jar-with-dependencies.jar:?]
		at com.twitter.finagle.http.codec.ResponseDecoder.messageReceived(ResponseDecoder.scala:20) [Distribution-Server-1.1.4-RELEASE-jar-with-dependencies.jar:?]
		at org.jboss.netty.channel.SimpleChannelHandler.handleUpstream(SimpleChannelHandler.java:88) [Distribution-Server-1.1.4-RELEASE-jar-with-dependencies.jar:?]
		at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:558) [Distribution-Server-1.1.4-RELEASE-jar-with-dependencies.jar:?]
		at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:786) [Distribution-Server-1.1.4-RELEASE-jar-with-dependencies.jar:?]
		at org.jboss.netty.handler.codec.http.HttpContentDecoder.messageReceived(HttpContentDecoder.java:103) [Distribution-Server-1.1.4-RELEASE-jar-with-dependencies.jar:?]
		at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70) [Distribution-Server-1.1.4-RELEASE-jar-with-dependencies.jar:?]
		at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:558) [Distribution-Server-1.1.4-RELEASE-jar-with-dependencies.jar:?]
		at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:786) [Distribution-Server-1.1.4-RELEASE-jar-with-dependencies.jar:?]
		at org.jboss.netty.handler.codec.http.HttpChunkAggregator.messageReceived(HttpChunkAggregator.java:148) [Distribution-Server-1.1.4-RELEASE-jar-with-dependencies.jar:?]
		at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70) [Distribution-Server-1.1.4-RELEASE-jar-with-dependencies.jar:?]
		at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:558) [Distribution-Server-1.1.4-RELEASE-jar-with-dependencies.jar:?]
		at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:786) [Distribution-Server-1.1.4-RELEASE-jar-with-dependencies.jar:?]
		at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:296) [Distribution-Server-1.1.4-RELEASE-jar-with-dependencies.jar:?]
		at org.jboss.netty.handler.codec.frame.FrameDecoder.unfoldAndFireMessageReceived(FrameDecoder.java:455) [Distribution-Server-1.1.4-RELEASE-jar-with-dependencies.jar:?]
		at org.jboss.netty.handler.codec.replay.ReplayingDecoder.callDecode(ReplayingDecoder.java:538) [Distribution-Server-1.1.4-RELEASE-jar-with-dependencies.jar:?]
		at org.jboss.netty.handler.codec.replay.ReplayingDecoder.messageReceived(ReplayingDecoder.java:437) [Distribution-Server-1.1.4-RELEASE-jar-with-dependencies.jar:?]
		at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70) [Distribution-Server-1.1.4-RELEASE-jar-with-dependencies.jar:?]
		at org.jboss.netty.handler.codec.http.HttpClientCodec.handleUpstream(HttpClientCodec.java:92) [Distribution-Server-1.1.4-RELEASE-jar-with-dependencies.jar:?]
		at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:558) [Distribution-Server-1.1.4-RELEASE-jar-with-dependencies.jar:?]
		at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:786) [Distribution-Server-1.1.4-RELEASE-jar-with-dependencies.jar:?]
		at org.jboss.netty.channel.SimpleChannelHandler.messageReceived(SimpleChannelHandler.java:142) [Distribution-Server-1.1.4-RELEASE-jar-with-dependencies.jar:?]
		at com.twitter.finagle.channel.ChannelStatsHandler.messageReceived(ChannelStatsHandler.scala:74) [Distribution-Server-1.1.4-RELEASE-jar-with-dependencies.jar:?]
		at org.jboss.netty.channel.SimpleChannelHandler.handleUpstream(SimpleChannelHandler.java:88) [Distribution-Server-1.1.4-RELEASE-jar-with-dependencies.jar:?]
		at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:558) [Distribution-Server-1.1.4-RELEASE-jar-with-dependencies.jar:?]
		at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:786) [Distribution-Server-1.1.4-RELEASE-jar-with-dependencies.jar:?]
		at org.jboss.netty.channel.SimpleChannelHandler.messageReceived(SimpleChannelHandler.java:142) [Distribution-Server-1.1.4-RELEASE-jar-with-dependencies.jar:?]
		at com.twitter.finagle.channel.ChannelRequestStatsHandler.messageReceived(ChannelRequestStatsHandler.scala:35) [Distribution-Server-1.1.4-RELEASE-jar-with-dependencies.jar:?]
		at org.jboss.netty.channel.SimpleChannelHandler.handleUpstream(SimpleChannelHandler.java:88) [Distribution-Server-1.1.4-RELEASE-jar-with-dependencies.jar:?]
		at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:558) [Distribution-Server-1.1.4-RELEASE-jar-with-dependencies.jar:?]
		at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:553) [Distribution-Server-1.1.4-RELEASE-jar-with-dependencies.jar:?]
		at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:268) [Distribution-Server-1.1.4-RELEASE-jar-with-dependencies.jar:?]
		at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:255) [Distribution-Server-1.1.4-RELEASE-jar-with-dependencies.jar:?]
		at org.jboss.netty.channel.socket.nio.NioWorker.read(NioWorker.java:84) [Distribution-Server-1.1.4-RELEASE-jar-with-dependencies.jar:?]
		at org.jboss.netty.channel.socket.nio.AbstractNioWorker.processSelectedKeys(AbstractNioWorker.java:471) [Distribution-Server-1.1.4-RELEASE-jar-with-dependencies.jar:?]
		at org.jboss.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:332) [Distribution-Server-1.1.4-RELEASE-jar-with-dependencies.jar:?]
		at org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:35) [Distribution-Server-1.1.4-RELEASE-jar-with-dependencies.jar:?]
		at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:102) [Distribution-Server-1.1.4-RELEASE-jar-with-dependencies.jar:?]
		at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42) [Distribution-Server-1.1.4-RELEASE-jar-with-dependencies.jar:?]
		at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [?:1.7.0_17]
		at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [?:1.7.0_17]
		at java.lang.Thread.run(Thread.java:722) [?:1.7.0_17]
	Caused by: java.lang.Exception: write while request pending
		... 139 more

**Comment by luciferous** [comment]
It's been two years so I'm going to assume it worked for him.
