### ISSUE TITLE
Finagle client will always result in "ChannelWriteException" when I run Finagle Server on Windows and use zookeeper for serverset

### ISSUE THREAD

**Issue by wenfengzhuo** [twitter/finagle#243]
I use Finagle framework to build my server and client, and use zookeeper for Finagle ServerSet. When I setup my dev environment on Linux/Mac, they works great. But When I setup my dev environment on Windows, namely I run the Finagle server on Windows, the finagle client always result in the following errors:
```
Exception in thread "main" com.twitter.finagle.ChannelWriteException: org.jboss.netty.channel.ConnectTimeoutException: connection timed out: [MyDomain]/192.168.1.130:5233
	at com.twitter.finagle.NoStacktrace(Unknown Source)
Caused by: org.jboss.netty.channel.ConnectTimeoutException: connection timed out: [MyDomain]/192.168.1.130:5233
	at org.jboss.netty.channel.socket.nio.NioClientBoss.processConnectTimeout(NioClientBoss.java:137)
	at org.jboss.netty.channel.socket.nio.NioClientBoss.process(NioClientBoss.java:83)
	at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:312)
	at org.jboss.netty.channel.socket.nio.NioClientBoss.run(NioClientBoss.java:42)
	at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
	at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:744)
```
When I run Finagle Server on Linux/Mac, and run Finagle Client on Windows, it works great, I am doubting that whether there exists some bugs when using finagle on Windows.

**Comment by mosesn** [comment]
@wenfengzhuo are you still running into this problem?  Since this is so old, I'm going to close this for now, but feel free to reopen if this is still causing you trouble.
