### ISSUE TITLE
LoadService gets stuck recursively descending into /sys

### ISSUE THREAD

**Issue by groestl** [twitter/finagle#309]
When spinning up our server on a rackspace instance (uname "Linux 3.2.0-60-generic #91-Ubuntu SMP Wed Feb 19 03:54:44 UTC 2014 x86_64 x86_64") the startup procedure gets stuck as soon as the finage client tries to set up LoadedStatsReceiver.

In the stack trace we see LoadService descending into a directory tree:
```
"main" prio=10 tid=0x00007f30b4010000 nid=0x7ff runnable [0x00007f30bdc00000]
   java.lang.Thread.State: RUNNABLE
	at java.io.UnixFileSystem.getBooleanAttributes0(Native Method)
	at java.io.UnixFileSystem.getBooleanAttributes(UnixFileSystem.java:242)
	at java.io.File.isDirectory(File.java:843)
	at com.twitter.finagle.util.ClassPath$$anonfun$com$twitter$finagle$util$ClassPath$$browseDir$1.apply(LoadService.scala:87)
	at com.twitter.finagle.util.ClassPath$$anonfun$com$twitter$finagle$util$ClassPath$$browseDir$1.apply(LoadService.scala:86)
	at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
--- repeated 69 times
	at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:108)
	at com.twitter.finagle.util.ClassPath$.com$twitter$finagle$util$ClassPath$$browseDir(LoadService.scala:86)
	at com.twitter.finagle.util.ClassPath$$anonfun$com$twitter$finagle$util$ClassPath$$browseDir$1.apply(LoadService.scala:88)
	at com.twitter.finagle.util.ClassPath$$anonfun$com$twitter$finagle$util$ClassPath$$browseDir$1.apply(LoadService.scala:86)
	at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
--- end repeat
	at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:108)
	at com.twitter.finagle.util.ClassPath$.com$twitter$finagle$util$ClassPath$$browseDir(LoadService.scala:86)
	at com.twitter.finagle.util.ClassPath$.browseUri(LoadService.scala:75)
	at com.twitter.finagle.util.ClassPath$$anonfun$browse$2.apply(LoadService.scala:38)
	at com.twitter.finagle.util.ClassPath$$anonfun$browse$2.apply(LoadService.scala:37)
	at scala.collection.TraversableLike$WithFilter$$anonfun$foreach$1.apply(TraversableLike.scala:772)
	at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:47)
	at scala.collection.TraversableLike$WithFilter.foreach(TraversableLike.scala:771)
	at com.twitter.finagle.util.ClassPath$.browse(LoadService.scala:37)
	at com.twitter.finagle.util.LoadService$.apply(LoadService.scala:156)
	at com.twitter.finagle.stats.LoadedStatsReceiver$.<init>(LoadedStatsReceiver.scala:11)
	at com.twitter.finagle.stats.LoadedStatsReceiver$.<clinit>(LoadedStatsReceiver.scala)
	at com.twitter.finagle.stats.DefaultStatsReceiver$.<init>(StatsReceiver.scala:238)
	at com.twitter.finagle.stats.DefaultStatsReceiver$.<clinit>(StatsReceiver.scala)
	at com.twitter.finagle.thrift.Protocols$.binaryFactory$default$4(Protocols.scala:55)
	at com.twitter.finagle.thrift.ThriftClientFramedCodecFactory.<init>(ThriftClientFramedCodec.scala:40)
	at com.twitter.finagle.thrift.ThriftClientFramedCodecFactory.<init>(ThriftClientFramedCodec.scala:42)
	at xs.peng.modules.places.services.DefaultPlacesService.init(DefaultPlacesService.java:67)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleElement.invoke(InitDestroyAnnotationBeanPostProcessor.java:349)
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleMetadata.invokeInitMethods(InitDestroyAnnotationBeanPostProcessor.java:300)
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:133)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsBeforeInitialization(AbstractAutowireCapableBeanFactory.java:407)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1545)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:539)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:475)
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:304)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:228)
	- locked <0x00000000d0ec8fe0> (a java.util.concurrent.ConcurrentHashMap)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:300)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:195)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:700)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:760)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:482)
	- locked <0x00000000d0f40458> (a java.lang.Object)
	at xs.peng.app.PengApplication.main(PengApplication.java:27)
```

and strace gives us an endless list of:
```
stat("/sys/devices/platform/reg-dummy/subsystem/devices/reg-dummy/subsystem/devices/reg-dummy/subsystem/devices/reg-dummy/subsystem/devices/reg-dummy/subsystem/devices/reg-dummy/subsystem/devices/reg-dummy/subsystem/devices/reg-dummy/subsystem/devices/reg-dummy/subsystem/devices/reg-dummy/subsystem/devices/reg-dummy/subsystem/devices/reg-dummy/subsystem/devices/reg-dummy/subsystem/devices/reg-dummy/subsystem/devices/reg-dummy/subsystem/devices/reg-dummy/subsystem/devices/reg-dummy/subsystem/devices/reg-dummy/subsystem/devices/reg-dummy/subsystem/devices/serial8250/tty/ttyS17/device/tty/ttyS19/device/tty/ttyS17/uevent", {st_mode=S_IFREG|0644, st_size=4096, ...}) = 0
stat("/sys/devices/platform/reg-dummy/subsystem/devices/reg-dummy/subsystem/devices/reg-dummy/subsystem/devices/reg-dummy/subsystem/devices/reg-dummy/subsystem/devices/reg-dummy/subsystem/devices/reg-dummy/subsystem/devices/reg-dummy/subsystem/devices/reg-dummy/subsystem/devices/reg-dummy/subsystem/devices/reg-dummy/subsystem/devices/reg-dummy/subsystem/devices/reg-dummy/subsystem/devices/reg-dummy/subsystem/devices/reg-dummy/subsystem/devices/reg-dummy/subsystem/devices/reg-dummy/subsystem/devices/reg-dummy/subsystem/devices/reg-dummy/subsystem/devices/serial8250/tty/ttyS17/device/tty/ttyS19/device/tty/ttyS17/dev", {st_mode=S_IFREG|0444, st_size=4096, ...}) = 0
stat("/sys/devices/platform/reg-dummy/subsystem/devices/reg-dummy/subsystem/devices/reg-dummy/subsystem/devices/reg-dummy/subsystem/devices/reg-dummy/subsystem/devices/reg-dummy/subsystem/devices/reg-dummy/subsystem/devices/reg-dummy/subsystem/devices/reg-dummy/subsystem/devices/reg-dummy/subsystem/devices/reg-dummy/subsystem/devices/reg-dummy/subsystem/devices/reg-dummy/subsystem/devices/reg-dummy/subsystem/devices/reg-dummy/subsystem/devices/reg-dummy/subsystem/devices/reg-dummy/subsystem/devices/reg-dummy/subsystem/devices/reg-dummy/subsystem/devices/serial8250/tty/ttyS17/device/tty/ttyS19/device/tty/ttyS17/subsystem", 0x7f5044247730) = -1 ELOOP (Too many levels of symbolic links)
stat("/sys/devices/platform/reg-dummy/subsystem/devices/reg-dummy/subsystem/devices/reg-dummy/subsystem/devices/reg-dummy/subsystem/devices/reg-dummy/subsystem/devices/reg-dummy/subsystem/devices/reg-dummy/subsystem/devices/reg-dummy/subsystem/devices/reg-dummy/subsystem/devices/reg-dummy/subsystem/devices/reg-dummy/subsystem/devices/reg-dummy/subsystem/devices/reg-dummy/subsystem/devices/reg-dummy/subsystem/devices/reg-dummy/subsystem/devices/reg-dummy/subsystem/devices/reg-dummy/subsystem/devices/reg-dummy/subsystem/devices/reg-dummy/subsystem/devices/serial8250/tty/ttyS17/device/tty/ttyS19/device/tty/ttyS17/device", 0x7f5044247730) = -1 ELOOP (Too many levels of symbolic links)
...
```

**Comment by mosesn** [comment]
OK, I guess if folks setting / as cwd is a real thing, we should maybe exclude /sys explicitly?  @revisiond, @groestl would one of you like to make a pull request?

**Comment by mosesn** [comment]
I think #351 fixes this, but please reopen if you have further problems!

**Comment by bymzy** [comment]
this seems to happen to me .

i am using tranquility-core_2.11:0.83  and it depends on finagle-6.43.0 @mosesn 

here is what strace shows

> [pid 2231848] stat("/proc/self/task/1679940/cwd/proc/self/task/1679940/cwd/proc/self/task/1679940/cwd/proc/self/task/1679940/cwd/proc/self/task/1679940/cwd/proc/self/task/1679940/cwd/proc/self/task/1679940/cwd/proc/self/task/1679940/cwd/proc/self/task/1679940/cwd/proc/self/task/1679940/cwd/proc/self/task/1679940/cwd/proc/self/task/1679940/cwd/proc/self/task/1679940/cwd/proc/self/task/1679940/cwd/proc/self/task/1679940/cwd/proc/self/task/1679940/cwd/proc/self/task/1679940/cwd/proc/self/task/1679940/cwd/proc/self/task/1679940/cwd/proc/self/task/1679946/cwd/proc/3372439/task/3373015/fd/305", 0x7fe29d5d1460) = -1 ELOOP (Too many levels of symbolic links)
[pid 2231848] stat("/proc/self/task/1679940/cwd/proc/self/task/1679940/cwd/proc/self/task/1679940/cwd/proc/self/task/1679940/cwd/proc/self/task/1679940/cwd/proc/self/task/1679940/cwd/proc/self/task/1679940/cwd/proc/self/task/1679940/cwd/proc/self/task/1679940/cwd/proc/self/task/1679940/cwd/proc/self/task/1679940/cwd/proc/self/task/1679940/cwd/proc/self/task/1679940/cwd/proc/self/task/1679940/cwd/proc/self/task/1679940/cwd/proc/self/task/1679940/cwd/proc/self/task/1679940/cwd/proc/self/task/1679940/cwd/proc/self/task/1679940/cwd/proc/self/task/1679946/cwd/proc/3372439/task/3373015/fd/306", 0x7fe29d5d1460) = -1 ELOOP (Too many levels of symbolic links)
[pid 2231848] stat("/proc/self/task/1679940/cwd/proc/self/task/1679940/cwd/proc/self/task/1679940/cwd/proc/self/task/1679940/cwd/proc/self/task/1679940/cwd/proc/self/task/1679940/cwd/proc/self/task/1679940/cwd/proc/self/task/1679940/cwd/proc/self/task/1679940/cwd/proc/self/task/1679940/cwd/proc/self/task/1679940/cwd/proc/self/task/1679940/cwd/proc/self/task/1679940/cwd/proc/self/task/1679940/cwd/proc/self/task/1679940/cwd/proc/self/task/1679940/cwd/proc/self/task/1679940/cwd/proc/self/task/1679940/cwd/proc/self/task/1679940/cwd/proc/self/task/1679946/cwd/proc/3372439/task/3373015/fd/307", 0x7fe29d5d1460) = -1 ELOOP (Too many levels of symbolic links)

**Comment by bymzy** [comment]
@jdneumeyer77  is right，i restart my program in /root and it works fine

**Comment by lwmonster** [comment]
@mosesn  It happened again... 
with finagle-thrift_2.11-6.36.0.jar

> "resin-port-9527-162" #162 daemon prio=5 os_prio=0 tid=0x00007fe0440b5110 nid=0x2ea26 runnable [0x00007fde222c9000]
   java.lang.Thread.State: RUNNABLE
        at java.io.UnixFileSystem.getBooleanAttributes0(Native Method)
        at java.io.UnixFileSystem.getBooleanAttributes(UnixFileSystem.java:242)
        at java.io.File.isDirectory(File.java:849)
        at com.twitter.app.ClassPath$$anonfun$com$twitter$app$ClassPath$$browseDir$1.apply(ClassPath.scala:118)
        at com.twitter.app.ClassPath$$anonfun$com$twitter$app$ClassPath$$browseDir$1.apply(ClassPath.scala:117)
        at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
        at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:186)
        at com.twitter.app.ClassPath.com$twitter$app$ClassPath$$browseDir(ClassPath.scala:117)
        at com.twitter.app.ClassPath$$anonfun$com$twitter$app$ClassPath$$browseDir$1.apply(ClassPath.scala:119)
        at com.twitter.app.ClassPath$$anonfun$com$twitter$app$ClassPath$$browseDir$1.apply(ClassPath.scala:117)
        at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
        at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:186)
        at com.twitter.app.ClassPath.com$twitter$app$ClassPath$$browseDir(ClassPath.scala:117)
        at com.twitter.app.ClassPath$$anonfun$com$twitter$app$ClassPath$$browseDir$1.apply(ClassPath.scala:119)
        at com.twitter.app.ClassPath$$anonfun$com$twitter$app$ClassPath$$browseDir$1.apply(ClassPath.scala:117)
        at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
        at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:186)
        at com.twitter.app.ClassPath.com$twitter$app$ClassPath$$browseDir(ClassPath.scala:117)
        at com.twitter.app.ClassPath$$anonfun$com$twitter$app$ClassPath$$browseDir$1.apply(ClassPath.scala:119)
        at com.twitter.app.ClassPath$$anonfun$com$twitter$app$ClassPath$$browseDir$1.apply(ClassPath.scala:117)
        at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
        at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:186)
        at com.twitter.app.ClassPath.com$twitter$app$ClassPath$$browseDir(ClassPath.scala:117)
        at com.twitter.app.ClassPath$$anonfun$com$twitter$app$ClassPath$$browseDir$1.apply(ClassPath.scala:119)
        at com.twitter.app.ClassPath$$anonfun$com$twitter$app$ClassPath$$browseDir$1.apply(ClassPath.scala:117)
        at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
        at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:186)
        at com.twitter.app.ClassPath.com$twitter$app$ClassPath$$browseDir(ClassPath.scala:117)
        at com.twitter.app.ClassPath$$anonfun$com$twitter$app$ClassPath$$browseDir$1.apply(ClassPath.scala:119)
        at com.twitter.app.ClassPath$$anonfun$com$twitter$app$ClassPath$$browseDir$1.apply(ClassPath.scala:117)
        at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
        at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:186)
        at com.twitter.app.ClassPath.com$twitter$app$ClassPath$$browseDir(ClassPath.scala:117)
        at com.twitter.app.ClassPath$$anonfun$com$twitter$app$ClassPath$$browseDir$1.apply(ClassPath.scala:119)
        at com.twitter.app.ClassPath$$anonfun$com$twitter$app$ClassPath$$browseDir$1.apply(ClassPath.scala:117)
        at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
        at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:186)
        at com.twitter.app.ClassPath.com$twitter$app$ClassPath$$browseDir(ClassPath.scala:117)
        at com.twitter.app.ClassPath$$anonfun$com$twitter$app$ClassPath$$browseDir$1.apply(ClassPath.scala:119)
        at com.twitter.app.ClassPath$$anonfun$com$twitter$app$ClassPath$$browseDir$1.apply(ClassPath.scala:117)
        at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
        at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:186)
        at com.twitter.app.ClassPath.com$twitter$app$ClassPath$$browseDir(ClassPath.scala:117)
        at com.twitter.app.ClassPath$$anonfun$com$twitter$app$ClassPath$$browseDir$1.apply(ClassPath.scala:119)
        at com.twitter.app.ClassPath$$anonfun$com$twitter$app$ClassPath$$browseDir$1.apply(ClassPath.scala:117)

**Comment by lwmonster** [comment]
We make it work by change the dir when starting the service,  I don't think it's a good way to resolve the problem.

> @mosesn It happened again... with finagle-thrift_2.11-6.36.0.jar
> 
> > "resin-port-9527-162" #162 daemon prio=5 os_prio=0 tid=0x00007fe0440b5110 nid=0x2ea26 runnable [0x00007fde222c9000]
> > java.lang.Thread.State: RUNNABLE
> > at java.io.UnixFileSystem.getBooleanAttributes0(Native Method)
> > at java.io.UnixFileSystem.getBooleanAttributes(UnixFileSystem.java:242)
> > at java.io.File.isDirectory(File.java:849)
> > at com.twitter.app.ClassPath$anonfun$browseDir$1.apply(ClassPath.scala:118)
> > at com.twitter.app.ClassPath$anonfun$browseDir$1.apply(ClassPath.scala:117)
> > at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
> > at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:186)
> > at com.twitter.app.ClassPath.comtwitter$browseDir(ClassPath.scala:117)
> > at com.twitter.app.ClassPath$anonfun$browseDir$1.apply(ClassPath.scala:119)
> > at com.twitter.app.ClassPath$anonfun$browseDir$1.apply(ClassPath.scala:117)
> > at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
> > at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:186)
> > at com.twitter.app.ClassPath.comtwitter$browseDir(ClassPath.scala:117)
> > at com.twitter.app.ClassPath$anonfun$browseDir$1.apply(ClassPath.scala:119)
> > at com.twitter.app.ClassPath$anonfun$browseDir$1.apply(ClassPath.scala:117)
> > at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
> > at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:186)
> > at com.twitter.app.ClassPath.comtwitter$browseDir(ClassPath.scala:117)
> > at com.twitter.app.ClassPath$anonfun$browseDir$1.apply(ClassPath.scala:119)
> > at com.twitter.app.ClassPath$anonfun$browseDir$1.apply(ClassPath.scala:117)
> > at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
> > at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:186)
> > at com.twitter.app.ClassPath.comtwitter$browseDir(ClassPath.scala:117)
> > at com.twitter.app.ClassPath$anonfun$browseDir$1.apply(ClassPath.scala:119)
> > at com.twitter.app.ClassPath$anonfun$browseDir$1.apply(ClassPath.scala:117)
> > at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
> > at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:186)
> > at com.twitter.app.ClassPath.comtwitter$browseDir(ClassPath.scala:117)
> > at com.twitter.app.ClassPath$anonfun$browseDir$1.apply(ClassPath.scala:119)
> > at com.twitter.app.ClassPath$anonfun$browseDir$1.apply(ClassPath.scala:117)
> > at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
> > at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:186)
> > at com.twitter.app.ClassPath.comtwitter$browseDir(ClassPath.scala:117)
> > at com.twitter.app.ClassPath$anonfun$browseDir$1.apply(ClassPath.scala:119)
> > at com.twitter.app.ClassPath$anonfun$browseDir$1.apply(ClassPath.scala:117)
> > at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
> > at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:186)
> > at com.twitter.app.ClassPath.comtwitter$browseDir(ClassPath.scala:117)
> > at com.twitter.app.ClassPath$anonfun$browseDir$1.apply(ClassPath.scala:119)
> > at com.twitter.app.ClassPath$anonfun$browseDir$1.apply(ClassPath.scala:117)
> > at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
> > at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:186)
> > at com.twitter.app.ClassPath.comtwitter$browseDir(ClassPath.scala:117)
> > at com.twitter.app.ClassPath$anonfun$browseDir$1.apply(ClassPath.scala:119)
> > at com.twitter.app.ClassPath$anonfun$browseDir$1.apply(ClassPath.scala:117)
