### ISSUE TITLE
Simple https fetchURL fails with new API:

### ISSUE THREAD

**Issue by dlwh** [twitter/finagle#323]
This might be related to #167 

I can't seem to make https work with the new Http.fetchURL api. This example is given in http://twitter.github.io/finagle/guide/FAQ.html#how-do-i-configure-clients-and-servers-with-finagle-6-apis

Every other https url I've tried fails in the same way.

Am I doing something wrong? I'm using 6.22

```scala
scala> import com.twitter.finagle._
import com.twitter.finagle._

scala> val response = Http.fetchUrl("https://twitter.com/")
// snip! 

scala> import com.twitter.util._
import com.twitter.util._

scala> Await.result(response)
com.twitter.finagle.ChannelClosedException: Connection reset by peer at remote address: twitter.com/199.59.148.82:443
	at com.twitter.finagle.NoStacktrace(Unknown Source)
Caused by: java.io.IOException: Connection reset by peer
	at sun.nio.ch.FileDispatcherImpl.read0(Native Method)
	at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:39)
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:225)
	at sun.nio.ch.IOUtil.read(IOUtil.java:193)
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:359)
	at org.jboss.netty.channel.socket.nio.NioWorker.read(NioWorker.java:64)
	at org.jboss.netty.channel.socket.nio.AbstractNioWorker.process(AbstractNioWorker.java:108)
	at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:318)
	at org.jboss.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:89)
	at org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:178)
	at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
	at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:722)
```

**Comment by luciferous** [comment]
The original issue has been resolved.
