### ISSUE TITLE
Unresolved dependency trying to run console

### ISSUE THREAD

**Issue by matthewmichihara** [twitter/finagle#392]
`./sbt "project finagle-http" console` is repeatedly giving me the following --

```
in finagle/
› ./sbt "project finagle-http" console
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=1024m; support was removed in 8.0
[info] Loading project definition from /Users/mattm/Code/finagle/project
[info] Updating {file:/Users/mattm/Code/finagle/project/}finagle-build...
[info] Resolving org.apache.thrift#libthrift;0.5.0-1 ...
[warn] 	module not found: org.apache.thrift#libthrift;0.5.0-1
[warn] ==== typesafe-ivy-releases: tried
[warn]   https://repo.typesafe.com/typesafe/ivy-releases/org.apache.thrift/libthrift/0.5.0-1/ivys/ivy.xml
[warn] ==== sbt-plugin-releases: tried
[warn]   https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/org.apache.thrift/libthrift/0.5.0-1/ivys/ivy.xml
[warn] ==== local: tried
[warn]   /Users/mattm/.ivy2/local/org.apache.thrift/libthrift/0.5.0-1/ivys/ivy.xml
[warn] ==== public: tried
[warn]   https://repo1.maven.org/maven2/org/apache/thrift/libthrift/0.5.0-1/libthrift-0.5.0-1.pom
[warn] ==== sbt-plugin-releases: tried
[warn]   https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/org.apache.thrift/libthrift/0.5.0-1/ivys/ivy.xml
[info] Resolving org.fusesource.jansi#jansi;1.4 ...
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	::          UNRESOLVED DEPENDENCIES         ::
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	:: org.apache.thrift#libthrift;0.5.0-1: not found
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn]
[warn] 	Note: Unresolved dependencies path:
[warn] 		org.apache.thrift:libthrift:0.5.0-1
[warn] 		  +- com.twitter:scrooge-generator_2.10:3.19.0
[warn] 		  +- com.twitter:scrooge-sbt-plugin:3.19.0 (scalaVersion=2.10, sbtVersion=0.13) (/Users/mattm/Code/finagle/project/plugins.sbt#L4-5)
[warn] 		  +- default:finagle-build:0.1-SNAPSHOT (scalaVersion=2.10, sbtVersion=0.13)
sbt.ResolveException: unresolved dependency: org.apache.thrift#libthrift;0.5.0-1: not found
	at sbt.IvyActions$.sbt$IvyActions$$resolve(IvyActions.scala:291)
	at sbt.IvyActions$$anonfun$updateEither$1.apply(IvyActions.scala:188)
	at sbt.IvyActions$$anonfun$updateEither$1.apply(IvyActions.scala:165)
	at sbt.IvySbt$Module$$anonfun$withModule$1.apply(Ivy.scala:155)
	at sbt.IvySbt$Module$$anonfun$withModule$1.apply(Ivy.scala:155)
	at sbt.IvySbt$$anonfun$withIvy$1.apply(Ivy.scala:132)
	at sbt.IvySbt.sbt$IvySbt$$action$1(Ivy.scala:57)
	at sbt.IvySbt$$anon$4.call(Ivy.scala:65)
	at xsbt.boot.Locks$GlobalLock.withChannel$1(Locks.scala:93)
	at xsbt.boot.Locks$GlobalLock.xsbt$boot$Locks$GlobalLock$$withChannelRetries$1(Locks.scala:78)
	at xsbt.boot.Locks$GlobalLock$$anonfun$withFileLock$1.apply(Locks.scala:97)
	at xsbt.boot.Using$.withResource(Using.scala:10)
	at xsbt.boot.Using$.apply(Using.scala:9)
	at xsbt.boot.Locks$GlobalLock.ignoringDeadlockAvoided(Locks.scala:58)
	at xsbt.boot.Locks$GlobalLock.withLock(Locks.scala:48)
	at xsbt.boot.Locks$.apply0(Locks.scala:31)
	at xsbt.boot.Locks$.apply(Locks.scala:28)
	at sbt.IvySbt.withDefaultLogger(Ivy.scala:65)
	at sbt.IvySbt.withIvy(Ivy.scala:127)
	at sbt.IvySbt.withIvy(Ivy.scala:124)
	at sbt.IvySbt$Module.withModule(Ivy.scala:155)
	at sbt.IvyActions$.updateEither(IvyActions.scala:165)
	at sbt.Classpaths$$anonfun$sbt$Classpaths$$work$1$1.apply(Defaults.scala:1369)
	at sbt.Classpaths$$anonfun$sbt$Classpaths$$work$1$1.apply(Defaults.scala:1365)
	at sbt.Classpaths$$anonfun$doWork$1$1$$anonfun$87.apply(Defaults.scala:1399)
	at sbt.Classpaths$$anonfun$doWork$1$1$$anonfun$87.apply(Defaults.scala:1397)
	at sbt.Tracked$$anonfun$lastOutput$1.apply(Tracked.scala:37)
	at sbt.Classpaths$$anonfun$doWork$1$1.apply(Defaults.scala:1402)
	at sbt.Classpaths$$anonfun$doWork$1$1.apply(Defaults.scala:1396)
	at sbt.Tracked$$anonfun$inputChanged$1.apply(Tracked.scala:60)
	at sbt.Classpaths$.cachedUpdate(Defaults.scala:1419)
	at sbt.Classpaths$$anonfun$updateTask$1.apply(Defaults.scala:1348)
	at sbt.Classpaths$$anonfun$updateTask$1.apply(Defaults.scala:1310)
	at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
	at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
	at sbt.std.Transform$$anon$4.work(System.scala:63)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
	at sbt.Execute.work(Execute.scala:235)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
	at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
	at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
[error] (*:update) sbt.ResolveException: unresolved dependency: org.apache.thrift#libthrift;0.5.0-1: not found
Project loading failed: (r)etry, (q)uit, (l)ast, or (i)gnore?
```

HEAD is `26dae347b9ce7806d02f781ebbe528e86b724924`
Is there any other useful information I can provide?

**Comment by travisbrown** [comment]
Since you're in the `develop` branch, you'll need to be sure to [publish Util and Scrooge locally first](https://github.com/twitter/finagle/blob/develop/CONTRIBUTING.md#building-dependencies). In a quick experiment that fixes the issue for me.

What you're seeing (and that I can replicate by deleting this dependency from my Ivy cache) is unexpected, though—I'll take a look asap.

**Comment by mosesn** [comment]
libthrift 0.5.1 isn't in maven central, so make sure http://maven.twttr.com is on your list of resolvers.

**Comment by matthewmichihara** [comment]
ah didn't see the Util/Scrooge instructions. Working for me now, thanks!

**Comment by travisbrown** [comment]
@matthewmichihara I'm glad that helped! I'd like to leave this issue open until we figure out why that resolution step was failing, though. As @mosesn says, you need to have `maven.twttr.com` in your resolvers, but since you're trying to build a Finagle subproject that was already done for you.

**Comment by mosesn** [comment]
@travisbrown also, we shouldn't need libthrift for finagle-http, afaik.

**Comment by cevaris** [comment]
Had this issue as well.

This seems to fix the finagle dependencies issue.
```
# Util
git clone https://github.com/twitter/util
cd util
./sbt +publishLocal

# Ostrich
git clone https://github.com/twitter/ostrich
cd ostrich
./sbt +publishLocal
```

Now you should be able to clone the finagle repo and compile the projects.

**Comment by oshev** [comment]
@cevaris Thanks, but didn't work for me. :-/
