### ISSUE TITLE
newbie try to compile ..

### ISSUE THREAD

**Issue by dy8000** [twitter/finagle#460]
try to run the example by typing in finagle directory, missing anything?

sbt "project finagle-example" run

[info] Resolving jline#jline;2.12.1 ...
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	::          UNRESOLVED DEPENDENCIES         ::
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	:: com.twitter#util-app_2.11;6.32.0-SNAPSHOT: not found
[warn] 	:: com.twitter#util-cache_2.11;6.32.0-SNAPSHOT: not found
[warn] 	:: com.twitter#util-codec_2.11;6.32.0-SNAPSHOT: not found
[warn] 	:: com.twitter#util-collection_2.11;6.32.0-SNAPSHOT: not found
[warn] 	:: com.twitter#util-core_2.11;6.32.0-SNAPSHOT: not found
[warn] 	:: com.twitter#util-hashing_2.11;6.32.0-SNAPSHOT: not found
[warn] 	:: com.twitter#util-jvm_2.11;6.32.0-SNAPSHOT: not found
[warn] 	:: com.twitter#util-lint_2.11;6.32.0-SNAPSHOT: not found
[warn] 	:: com.twitter#util-logging_2.11;6.32.0-SNAPSHOT: not found
[warn] 	:: com.twitter#util-registry_2.11;6.32.0-SNAPSHOT: not found
[warn] 	:: com.twitter#util-stats_2.11;6.32.0-SNAPSHOT: not found
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 
[warn] 	Note: Unresolved dependencies path:
[warn] 		com.twitter:util-logging_2.11:6.32.0-SNAPSHOT (/Users/don/ScalaProj/finagle/project/Build.scala#L221)
[warn] 		  +- com.twitter:finagle-core_2.11:6.33.0-SNAPSHOT ()
[warn] 		com.twitter:util-stats_2.11:6.32.0-SNAPSHOT (/Users/don/ScalaProj/finagle/project/Build.scala#L221)
[warn] 		  +- com.twitter:finagle-core_2.11:6.33.0-SNAPSHOT ()
[warn] 		com.twitter:util-collection_2.11:6.32.0-SNAPSHOT ((com.twitter.scrooge.ScroogeSBT) ScroogeSBT.scala#L154)
[warn] 		  +- com.twitter:finagle-core_2.11:6.33.0-SNAPSHOT ()
[warn] 		com.twitter:util-codec_2.11:6.32.0-SNAPSHOT (/Users/don/ScalaProj/finagle/project/Build.scala#L221)
[warn] 		  +- com.twitter:finagle-core_2.11:6.33.0-SNAPSHOT ()
[warn] 		com.twitter:util-hashing_2.11:6.32.0-SNAPSHOT ((com.twitter.scrooge.ScroogeSBT) ScroogeSBT.scala#L154)
[warn] 		  +- com.twitter:finagle-core_2.11:6.33.0-SNAPSHOT ()
[warn] 		com.twitter:util-core_2.11:6.32.0-SNAPSHOT (/Users/don/ScalaProj/finagle/project/Build.scala#L221)
[warn] 		  +- com.twitter:finagle-core_2.11:6.33.0-SNAPSHOT ()
[warn] 		com.twitter:util-cache_2.11:6.32.0-SNAPSHOT (/Users/don/ScalaProj/finagle/project/Build.scala#L221)
[warn] 		  +- com.twitter:finagle-core_2.11:6.33.0-SNAPSHOT ()
[warn] 		com.twitter:util-registry_2.11:6.32.0-SNAPSHOT (/Users/don/ScalaProj/finagle/project/Build.scala#L221)
[warn] 		  +- com.twitter:finagle-core_2.11:6.33.0-SNAPSHOT ()
[warn] 		com.twitter:util-app_2.11:6.32.0-SNAPSHOT (/Users/don/ScalaProj/finagle/project/Build.scala#L221)
[warn] 		  +- com.twitter:finagle-core_2.11:6.33.0-SNAPSHOT ()
[warn] 		com.twitter:util-jvm_2.11:6.32.0-SNAPSHOT ((com.twitter.scrooge.ScroogeSBT) ScroogeSBT.scala#L154)
[warn] 		  +- com.twitter:finagle-core_2.11:6.33.0-SNAPSHOT ()
[warn] 		com.twitter:util-lint_2.11:6.32.0-SNAPSHOT ((com.twitter.scrooge.ScroogeSBT) ScroogeSBT.scala#L154)
[warn] 		  +- com.twitter:finagle-core_2.11:6.33.0-SNAPSHOT ()
sbt.ResolveException: unresolved dependency: com.twitter#util-app_2.11;6.32.0-SNAPSHOT: not found
unresolved dependency: com.twitter#util-cache_2.11;6.32.0-SNAPSHOT: not found
unresolved dependency: com.twitter#util-codec_2.11;6.32.0-SNAPSHOT: not found
unresolved dependency: com.twitter#util-collection_2.11;6.32.0-SNAPSHOT: not found
unresolved dependency: com.twitter#util-core_2.11;6.32.0-SNAPSHOT: not found
unresolved dependency: com.twitter#util-hashing_2.11;6.32.0-SNAPSHOT: not found
unresolved dependency: com.twitter#util-jvm_2.11;6.32.0-SNAPSHOT: not found
unresolved dependency: com.twitter#util-lint_2.11;6.32.0-SNAPSHOT: not found
unresolved dependency: com.twitter#util-logging_2.11;6.32.0-SNAPSHOT: not found
unresolved dependency: com.twitter#util-registry_2.11;6.32.0-SNAPSHOT: not found
unresolved dependency: com.twitter#util-stats_2.11;6.32.0-SNAPSHOT: not found
	at sbt.IvyActions$.sbt$IvyActions$$resolve(IvyActions.scala:294)
	at sbt.IvyActions$$anonfun$updateEither$1.apply(IvyActions.scala:191)
	at sbt.IvyActions$$anonfun$updateEither$1.apply(IvyActions.scala:168)
	at sbt.IvySbt$Module$$anonfun$withModule$1.apply(Ivy.scala:155)
	at sbt.IvySbt$Module$$anonfun$withModule$1.apply(Ivy.scala:155)
	at sbt.IvySbt$$anonfun$withIvy$1.apply(Ivy.scala:132)
	at sbt.IvySbt.sbt$IvySbt$$action$1(Ivy.scala:57)
	at sbt.IvySbt$$anon$4.call(Ivy.scala:65)
	at xsbt.boot.Locks$GlobalLock.withChannel$1(Locks.scala:93)
	at xsbt.boot.Locks$GlobalLock.xsbt$boot$Locks$GlobalLock$$withChannelRetries$1(Locks.scala:78)
	at xsbt.boot.Locks$GlobalLock$$anonfun$withFileLock$1.apply(Locks.scala:97)
	at xsbt.boot.Using$.withResource(Using.scala:10)

**Comment by mosesn** [comment]
Welcome, @dy8000!  Check out the [CONTRIBUTING.md][0] guide, which describes how to build the project.  If you just want to try building it, I'd suggest going to the `master` branch, which will use the stable versions in maven central.  If you want to contribute back, I'd encourage you to follow the instructions to check out the dependent repositories.  The `develop` branch has the newest code, which may depend on changes in other repositories.

[0]: https://github.com/twitter/finagle/blob/develop/CONTRIBUTING.md

**Comment by dy8000** [comment]
Thanks, finally get to to compile the dev branch. But I only want to clone the master not dev branch, and therefore can use maven repo, and use the examples to start developing. I did clone the master branch separately, but have other dependency problems, when trying : sbt "project finagle-example" run . Not being proficient in SBT feel very cripple. In Comparison Maven is simpler to get started. Any advise will appreciate.

**Comment by mosesn** [comment]
@dy8000 sorry to hear you're having trouble.  However, the good news is that sbt is the community standard in scala, so it'll be worth it for you to learn sbt.

What are the dependency problems you're running into?

**Comment by dy8000** [comment]
I've that resolved. I think sbt evicts some libraries. -thanks.

**Comment by drupadpanchal** [comment]
**master** branch compilation failed for me with a 'module not found error: com.twitter#scrooge-generator_2.10;4.4.0'.  

The workaround I used was to update the 'scrooge-sbt-plugin' version to 4.5.0 in project/plugins.sbt. 

[Note: This is the same 'scrooge-sbt-plugin' version used in the **develop** branch]

Detailed stacktrace of the error (for SE indexing)
`bash-4.1$ ./sbt compile
[info] Loading project definition from /sources/finagle/project
[info] Updating {file:/sources/finagle/project/}finagle-build...
[info] Resolving com.twitter#scrooge-generator_2.10;4.4.0 ...
[warn] 	module not found: com.twitter#scrooge-generator_2.10;4.4.0
[warn] ==== typesafe-ivy-releases: tried
[warn]   https://repo.typesafe.com/typesafe/ivy-releases/com.twitter/scrooge-generator_2.10/4.4.0/ivys/ivy.xml
[warn] ==== sbt-plugin-releases: tried
[warn]   https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/com.twitter/scrooge-generator_2.10/4.4.0/ivys/ivy.xml
[warn] ==== local: tried
[warn]   /.ivy2/local/com.twitter/scrooge-generator_2.10/4.4.0/ivys/ivy.xml
[warn] ==== public: tried
[warn]   https://repo1.maven.org/maven2/com/twitter/scrooge-generator_2.10/4.4.0/scrooge-generator_2.10-4.4.0.pom
[warn] ==== sbt-plugin-releases: tried
[warn]   https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/com.twitter/scrooge-generator_2.10/4.4.0/ivys/ivy.xml
[warn] ==== twitter-repo: tried
[warn]   https://maven.twttr.com/com/twitter/scrooge-generator_2.10/4.4.0/scrooge-generator_2.10-4.4.0.pom
[info] Resolving org.fusesource.jansi#jansi;1.4 ...
[info] downloading https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/com.twitter/scrooge-sbt-plugin/scala_2.10/sbt_0.13/4.4.0/jars/scrooge-sbt-plugin.jar ...
[info] 	[SUCCESSFUL ] com.twitter#scrooge-sbt-plugin;4.4.0!scrooge-sbt-plugin.jar (3947ms)
[info] downloading https://repo1.maven.org/maven2/io/netty/netty/3.6.4.Final/netty-3.6.4.Final.jar ...
[info] 	[SUCCESSFUL ] io.netty#netty;3.6.4.Final!netty.jar(bundle) (858ms)
[info] downloading https://repo1.maven.org/maven2/commons-codec/commons-codec/1.4/commons-codec-1.4.jar ...
[info] 	[SUCCESSFUL ] commons-codec#commons-codec;1.4!commons-codec.jar (325ms)
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	::          UNRESOLVED DEPENDENCIES         ::
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	:: com.twitter#scrooge-generator_2.10;4.4.0: not found
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 
[warn] 	Note: Unresolved dependencies path:
[warn] 		com.twitter:scrooge-generator_2.10:4.4.0
[warn] 		  +- com.twitter:scrooge-sbt-plugin:4.4.0 (sbtVersion=0.13, scalaVersion=2.10) (/sources/finagle/project/plugins.sbt#L6-7)
[warn] 		  +- default:finagle-build:0.1-SNAPSHOT (sbtVersion=0.13, scalaVersion=2.10)
sbt.ResolveException: unresolved dependency: com.twitter#scrooge-generator_2.10;4.4.0: not found
	at sbt.IvyActions$.sbt$IvyActions$$resolve(IvyActions.scala:294)
	at sbt.IvyActions$$anonfun$updateEither$1.apply(IvyActions.scala:191)
	at sbt.IvyActions$$anonfun$updateEither$1.apply(IvyActions.scala:168)
	at sbt.IvySbt$Module$$anonfun$withModule$1.apply(Ivy.scala:155)
	at sbt.IvySbt$Module$$anonfun$withModule$1.apply(Ivy.scala:155)
	at sbt.IvySbt$$anonfun$withIvy$1.apply(Ivy.scala:132)
	at sbt.IvySbt.sbt$IvySbt$$action$1(Ivy.scala:57)
	at sbt.IvySbt$$anon$4.call(Ivy.scala:65)
	at xsbt.boot.Locks$GlobalLock.withChannel$1(Locks.scala:93)
	at xsbt.boot.Locks$GlobalLock.xsbt$boot$Locks$GlobalLock$$withChannelRetries$1(Locks.scala:78)
	at xsbt.boot.Locks$GlobalLock$$anonfun$withFileLock$1.apply(Locks.scala:97)
	at xsbt.boot.Using$.withResource(Using.scala:10)
	at xsbt.boot.Using$.apply(Using.scala:9)
	at xsbt.boot.Locks$GlobalLock.ignoringDeadlockAvoided(Locks.scala:58)
	at xsbt.boot.Locks$GlobalLock.withLock(Locks.scala:48)
	at xsbt.boot.Locks$.apply0(Locks.scala:31)
	at xsbt.boot.Locks$.apply(Locks.scala:28)
	at sbt.IvySbt.withDefaultLogger(Ivy.scala:65)
	at sbt.IvySbt.withIvy(Ivy.scala:127)
	at sbt.IvySbt.withIvy(Ivy.scala:124)
	at sbt.IvySbt$Module.withModule(Ivy.scala:155)
	at sbt.IvyActions$.updateEither(IvyActions.scala:168)
	at sbt.Classpaths$$anonfun$sbt$Classpaths$$work$1$1.apply(Defaults.scala:1392)
	at sbt.Classpaths$$anonfun$sbt$Classpaths$$work$1$1.apply(Defaults.scala:1388)
	at sbt.Classpaths$$anonfun$doWork$1$1$$anonfun$90.apply(Defaults.scala:1422)
	at sbt.Classpaths$$anonfun$doWork$1$1$$anonfun$90.apply(Defaults.scala:1420)
	at sbt.Tracked$$anonfun$lastOutput$1.apply(Tracked.scala:37)
	at sbt.Classpaths$$anonfun$doWork$1$1.apply(Defaults.scala:1425)
	at sbt.Classpaths$$anonfun$doWork$1$1.apply(Defaults.scala:1419)
	at sbt.Tracked$$anonfun$inputChanged$1.apply(Tracked.scala:60)
	at sbt.Classpaths$.cachedUpdate(Defaults.scala:1442)
	at sbt.Classpaths$$anonfun$updateTask$1.apply(Defaults.scala:1371)
	at sbt.Classpaths$$anonfun$updateTask$1.apply(Defaults.scala:1325)
	at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
	at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
	at sbt.std.Transform$$anon$4.work(System.scala:63)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
	at sbt.Execute.work(Execute.scala:235)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
	at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
	at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:744)
[error] (*:update) sbt.ResolveException: unresolved dependency: com.twitter#scrooge-generator_2.10;4.4.0: not found`
