### ISSUE TITLE
netty4: no channel stats on clients

### ISSUE THREAD

**Issue by olix0r** [twitter/finagle#506]
finagle-netty4 includes a ChannelStatsHandler (analogous to netty3's channel stats handler). However, it appears that netty4 channel stats are only recorded on servers and not clients:
```
:; git grep -Fl ChannelStatsHandler finagle-netty4/src/main
finagle-netty4/src/main/scala/com/twitter/finagle/netty4/channel/ChannelStatsHandler.scala
finagle-netty4/src/main/scala/com/twitter/finagle/netty4/channel/Netty4ServerChannelInitializer.scala
```

It seems stats just aren't wired into the netty4 client yet. I'm happy to give it a go if no one's working on it.

**Comment by olix0r** [comment]
Hm... While this allows some of my tests to pass, others fail:

```
WARNING: ChannelStatsHandler caught an exception
java.lang.NullPointerException
	at com.twitter.finagle.netty4.channel.ChannelStatsHandler.channelInactive(ChannelStatsHandler.scala:104)
	at io.netty.channel.ChannelHandlerInvokerUtil.invokeChannelInactiveNow(ChannelHandlerInvokerUtil.java:56)
	at io.netty.channel.DefaultChannelHandlerInvoker.invokeChannelInactive(DefaultChannelHandlerInvoker.java:93)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:342)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:124)
	at io.netty.channel.DefaultChannelPipeline.fireChannelInactive(DefaultChannelPipeline.java:1060)
	at io.netty.channel.AbstractChannel$AbstractUnsafe$7.run(AbstractChannel.java:747)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:339)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:373)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:742)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at com.twitter.finagle.util.ProxyThreadFactory$$anonfun$newProxiedRunnable$1$$anon$1.run(ProxyThreadFactory.scala:19)
	at java.lang.Thread.run(Thread.java:745)
```

fails at:
```scala
override def channelInactive(ctx: ChannelHandlerContext) {
    closeChans.incr()
    val channelStats = ctx.attr(ConnectionStatsKey).get

    connectionReceivedBytes.add(channelStats.bytesRead.get)
```

**Comment by olix0r** [comment]
good news is the rest of my end-to-end ests pass when i don't check connection stats...  i'll dig into this a bit today

**Comment by dschobel** [comment]
looking at `AbstractChannel` they guard firing channelInactive with `wasActive && !isActive())` so the netty contract seems to be the sane one that a channel needs to become active before it can become inactive.

I would start by confirming that nothing else in the client pipeline is swallowing the channelActive message.

we should have all handlers in the default pipeline covered in `com.twitter.finagle.netty4.channel.HandlerEventTest` which tests that they're not swallowing messages but it's possible we missed one.
