### ISSUE TITLE
thrift failed error: /bin/sh: 1: /tmp/thrift-...: Permission denied

### ISSUE THREAD

**Issue by doronl** [twitter/finagle#551]
I downloaded an open source project and got:  Permission denied while trying to build it (mvn clean install).

I got the following error log:

[INFO] --- maven-finagle-thrift-plugin:0.0.9:compile (thrift-sources) @ secor ---
[INFO] compiling thrift files [/home/doron.levi/development/inc/secor/src/main/thrift/secor.thrift] with generators [finagle]
[INFO] copying /thrift/thrift-finagle.linux64 to /tmp/thrift-finagle1787813194432256918
[INFO] running [-o, /home/myuser/development/inc/secor/target/generated-sources/thrift, --gen, java, /home/myuser/development/inc/secor/src/main/thrift/secor.thrift]
[ERROR] thrift failed output: 
[ERROR] thrift failed error: /bin/sh: 1: /tmp/thrift-finagle1787813194432256918: Permission denied

Using maven version 3.2.1

When runing maven with -X I got in the log:

[ERROR] Failed to execute goal com.twitter:maven-finagle-thrift-plugin:0.0.9:compile (thrift-sources) on project secor: thrift did not exit cleanly. Review output for more information. -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal com.twitter:maven-finagle-thrift-plugin:0.0.9:compile (thrift-sources) on project secor: thrift did not exit cleanly. Review output for more information.
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:212)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:108)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:76)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:116)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:361)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:155)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:584)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:213)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:157)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.MojoFailureException: thrift did not exit cleanly. Review output for more information.
	at com.twitter.FinagleThriftRunner.compile(FinagleThriftRunner.java:86)
	at com.twitter.AbstractFinagleThriftMojo.execute(AbstractFinagleThriftMojo.java:191)
	at com.twitter.FinagleThriftCompileMojo.execute(FinagleThriftCompileMojo.java:22)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:133)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
	... 19 more

My env:

Java version: 1.8.0_101, vendor: Oracle Corporation
Java home: /usr/lib/jvm/java-8-oracle/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "3.13.0-95-generic", arch: "amd64", family: "unix"

Just cloned the https://github.com/pinterest/secor and run mvn clean install... this is not happening on my mac laptop

**Comment by mosesn** [comment]
@doronl the maven-finagle-thrift-plugin is really old, and unfortunately, also really dead.  It never supported windows, and even when we supported it, we just told people to use a VM if you really had to build on windows.  If you're really dedicated to windows, you might have better luck switching to scrooge, which is not deprecated, and has a maven plugin, and there will at least be a small chance that it will work for you.

It might be better to ask the pinterest/secor folks for advice here?  Closing for now, please reopen if you have more questions.

**Comment by doronl** [comment]
I see, anyway I solved this by executing: sudo mount -o remount,exec /tmp.

Thanks anyway!
Doron
