### ISSUE TITLE
LostSyncException in finagle-mysql

### ISSUE THREAD

**Issue by iwag** [twitter/finagle#573]
Seemingly, finagle-mysql can't handle some errors.

### Expected behavior

Returns proper error message.

### Actual behavior

Sometimes it returns LostSyncException with UnderflowException or IndexOutOfBoundsException. 

```
FATAL: Exception propagated to the default monitor (upstream address: n/a, downstream address: /127.0.0.1:43306, label: 127.0.0.1:43306).
com.twitter.finagle.mysql.LostSyncException: com.twitter.finagle.util.BufReader$UnderflowException: tried to read a byte when remaining bytes was 0
	at com.twitter.finagle.mysql.ClientDispatcher$$anonfun$com$twitter$finagle$mysql$ClientDispatcher$$const$1.applyOrElse(ClientDispatcher.scala:102)
	at com.twitter.finagle.mysql.ClientDispatcher$$anonfun$com$twitter$finagle$mysql$ClientDispatcher$$const$1.applyOrElse(ClientDispatcher.scala:102)
	at com.twitter.util.Throw.rescue(Try.scala:235)
	at com.twitter.finagle.mysql.ClientDispatcher$.com$twitter$finagle$mysql$ClientDispatcher$$const(ClientDispatcher.scala:102)
	at com.twitter.finagle.mysql.ClientDispatcher$$anonfun$4.apply(ClientDispatcher.scala:142)
	at com.twitter.finagle.mysql.ClientDispatcher$$anonfun$4.apply(ClientDispatcher.scala:141)
	at com.twitter.util.Future$$anonfun$flatMap$1.apply(Future.scala:1089)
	at com.twitter.util.Future$$anonfun$flatMap$1.apply(Future.scala:1088)
	at com.twitter.util.Promise$Transformer.liftedTree1$1(Promise.scala:107)
	at com.twitter.util.Promise$Transformer.k(Promise.scala:107)
	at com.twitter.util.Promise$Transformer.apply(Promise.scala:117)
	at com.twitter.util.Promise$Transformer.apply(Promise.scala:98)
	at com.twitter.util.Promise$$anon$1.run(Promise.scala:421)
	at com.twitter.concurrent.LocalScheduler$Activation.run(Scheduler.scala:200)
	at com.twitter.concurrent.LocalScheduler$Activation.submit(Scheduler.scala:158)
	at com.twitter.concurrent.LocalScheduler.submit(Scheduler.scala:272)
	at com.twitter.concurrent.Scheduler$.submit(Scheduler.scala:108)
	at com.twitter.util.Promise.runq(Promise.scala:405)
	at com.twitter.util.Promise.updateIfEmpty(Promise.scala:801)
	at com.twitter.util.Promise.update(Promise.scala:775)
	at com.twitter.util.Promise.setValue(Promise.scala:751)
	at com.twitter.concurrent.AsyncQueue.offer(AsyncQueue.scala:120)
	at com.twitter.finagle.netty3.transport.ChannelTransport.handleUpstream(ChannelTransport.scala:55)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
	at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
	at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:296)
	at org.jboss.netty.handler.codec.frame.FrameDecoder.unfoldAndFireMessageReceived(FrameDecoder.java:462)
	at org.jboss.netty.handler.codec.frame.FrameDecoder.callDecode(FrameDecoder.java:443)
	at org.jboss.netty.handler.codec.frame.FrameDecoder.messageReceived(FrameDecoder.java:303)
	at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
	at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
	at org.jboss.netty.channel.SimpleChannelHandler.messageReceived(SimpleChannelHandler.java:142)
	at com.twitter.finagle.netty3.channel.ChannelStatsHandler.messageReceived(ChannelStatsHandler.scala:68)
	at org.jboss.netty.channel.SimpleChannelHandler.handleUpstream(SimpleChannelHandler.java:88)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
	at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
	at org.jboss.netty.channel.SimpleChannelHandler.messageReceived(SimpleChannelHandler.java:142)
	at com.twitter.finagle.netty3.channel.ChannelRequestStatsHandler.messageReceived(ChannelRequestStatsHandler.scala:32)
	at org.jboss.netty.channel.SimpleChannelHandler.handleUpstream(SimpleChannelHandler.java:88)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:559)
	at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:268)
	at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:255)
	at org.jboss.netty.channel.socket.nio.NioWorker.read(NioWorker.java:88)
	at org.jboss.netty.channel.socket.nio.AbstractNioWorker.process(AbstractNioWorker.java:108)
	at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:337)
	at org.jboss.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:89)
	at org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:178)
	at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
	at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at com.twitter.finagle.util.ProxyThreadFactory$$anonfun$newProxiedRunnable$1$$anon$1.run(ProxyThreadFactory.scala:19)
	at java.lang.Thread.run(Thread.java:745)
Caused by: com.twitter.finagle.util.BufReader$UnderflowException: tried to read a byte when remaining bytes was 0
	at com.twitter.finagle.util.BufReaderImpl.readByte(BufReader.scala:266)
	at com.twitter.finagle.util.ProxyBufReader$class.readByte(BufReader.scala:158)
	at com.twitter.finagle.mysql.transport.MysqlBufReader.readByte(MysqlBuf.scala:44)
	at com.twitter.finagle.mysql.transport.MysqlBufReader.readNullTerminatedBytes(MysqlBuf.scala:62)
	at com.twitter.finagle.mysql.HandshakeInit$.decode(Result.scala:27)
	at com.twitter.finagle.mysql.HandshakeInit$.decode(Result.scala:23)
	at com.twitter.finagle.mysql.Decoder$$anonfun$apply$1.apply(Result.scala:15)
	at com.twitter.finagle.mysql.Decoder$$anonfun$apply$1.apply(Result.scala:15)
	at com.twitter.util.Try$.apply(Try.scala:15)
	at com.twitter.finagle.mysql.Decoder$class.apply(Result.scala:15)
	at com.twitter.finagle.mysql.HandshakeInit$.apply(Result.scala:23)
	... 51 more
```

in finagle-6.35.0 ~ 6.40.0.

```
com.twitter.finagle.exp.mysql.LostSyncException: java.lang.IndexOutOfBoundsException: Readable byte limit exceeded: 23
	at com.twitter.finagle.exp.mysql.ClientDispatcher$$anonfun$com$twitter$finagle$exp$mysql$ClientDispatcher$$const$1.applyOrElse(ClientDispatcher.scala:92)
	at 
```

in finalge-6.34.0.

### Steps to reproduce the behavior

```scala
import com.twitter.util.{Await, Future}
import com.twitter.finagle.client.{DefaultPool, StackClient}
import com.twitter.finagle.Mysql
import com.twitter.finagle.mysql._

object Server extends App {
  val mysql = Mysql.Client(params = StackClient.defaultParams)
    .withCredentials("test", "test")
    .withDatabase("test")
    .newRichClient("127.0.0.1:3306")

    Await.result(Future.join(for (i <- 1 to 10) yield mysql.ping))

    Thread.sleep(10000)

    Await.result(Future.join(for (i <- 1 to 10) yield mysql.ping))
}
```

```
$ docker run -e MYSQL_ROOT_PASSWORD=root -e MYSQL_PASSWORD=test -e MYSQL_USER=test -e MYSQL_DATABASE=test -p 3306:3306 -d mysql:5.6 --max-connections=1
$ sbt run
```

**Comment by iwag** [comment]
probably similar issue https://github.com/twitter/finagle/issues/439

**Comment by mosesn** [comment]
@iwag hmm, interesting.  it looks like we misinterpret a mysql response, so our protocol implementation isn't quite right.  what do you think about taking a stab at this?

**Comment by iwag** [comment]
Okay 😄  I will try.
But I'm not familiar with the implementation. 
Do you have any ideas where I start to do ?

**Comment by mosesn** [comment]
@iwag I'd suggest looking at where we get the UnderflowException in the stack trace, then trace back through the stack trace to figure out where we make a bad assumption about what the mysql protocol will return to us.  It looks like the mysql ClientDispatcher might be a good place to look?  Thanks!  Please let me know if you have any more questions about it.

**Comment by zarinfam** [comment]
I have this problem too.

**Comment by nepthar** [comment]
@iwag have you had a chance to take a look at this?

**Comment by iwag** [comment]
@nepthar thanks for reminding me. I forgot to post my idea after digging for that. Anyway, I'm not familiar with MySQL but I suppose this is kind of correct behavior. [MySQL Handshake phase](https://github.com/twitter/finagle/blob/master/finagle-mysql/src/main/scala/com/twitter/finagle/mysql/Result.scala#L27) fails and then LostSyncException occurs (see the stack trace).  In this case, I set to "--max-connections=1" and try hundreds of connections to MySQL server so the server doesn't send correct Handshake packet. 
However, this exception is a little confusing, isn't it? How about if making new type of exception? What do you think?

**Comment by nepthar** [comment]
A new exception makes a sense to me, or at the very least a note in the exception. ("Exception in mysql handshake: blah blah").

Just so I make sure I understand correctly - occasionally mysql server fails to deliver a properly formed handshake? Is this from some kind of connection failure or something?

**Comment by iwag** [comment]
Sounds great! > a note in the exception.
It can be small amount of modification. I like it.

This is a kind of connection failure. MySQL server refuses to connect because of overcapacity. finagle-mysql seems to be unable to handle a error which occurs in handshake phase.

**Comment by nepthar** [comment]
Cool. Okay, moving forward with a new exception sounds pretty good to me. Take a look at our docs on how to use [FailureFlags](https://twitter.github.io/finagle/guide/developers/SignalingFailure.html#creating-exceptions-with-failureflags). It seems like this failure can be automatically retried, so make sure to flag it Retryable.

Let me know if you run into any snags. Thanks!

**Comment by nepthar** [comment]
@iwag Any luck with this?

**Comment by smlance** [comment]
I'm unable to reproduce this with Finagle 18.8.0 and MySQL 8.0.12. @iwag Are you still seeing this issue?

**Comment by smlance** [comment]
Sorry, wasn't passing the max connections flag. I see this error locally.

**Comment by smlance** [comment]
This should be resolved as of https://github.com/twitter/finagle/commit/89484ecc216b94ac1dcdfadc16d9f179ccf3c345.

**Comment by iwag** [comment]
@smlance Great work! Thanks
