### ISSUE TITLE
IllegalArgumentException: bound must be positive

### ISSUE THREAD

**Issue by codeape** [twitter/finagle#641]
We are getting IllegalArgumentException: bound must be positive every second for an app. 

### Expected behavior

No IllegalArgumentException about every second.

### Actual behavior

About every second we get an IllegalArgumentException. I can not understand where to start looking for the problem. Maybe I am doing something wrong? or is this a bug? I need some help to understand where to start to look for the root cause of this. We are using Finagle 6.43.0.

`2017-06-22 20:31:57,407 ERROR monitor - Exception propagated to the root monitor! traceId=397cf9f1ab0f7ac0 
java.lang.IllegalArgumentException: bound must be positive
	at java.util.concurrent.ThreadLocalRandom.nextLong(ThreadLocalRandom.java:403) ~[na:1.8.0_65]
	at com.twitter.finagle.util.Rng$$anon$2.nextLong(Rng.scala:70) ~[finagle-core_2.11-6.30.0.jar:6.30.0]
	at com.twitter.finagle.service.Backoff$.com$twitter$finagle$service$Backoff$$next$4(Backoff.scala:127) ~[finagle-core_2.11-6.30.0.jar:6.30.0]
	at com.twitter.finagle.service.Backoff$$anonfun$com$twitter$finagle$service$Backoff$$next$4$1.apply(Backoff.scala:128) ~[finagle-core_2.11-6.30.0.jar:6.30.0]
	at com.twitter.finagle.service.Backoff$$anonfun$com$twitter$finagle$service$Backoff$$next$4$1.apply(Backoff.scala:128) ~[finagle-core_2.11-6.30.0.jar:6.30.0]
	at scala.collection.immutable.Stream$Cons.tail(Stream.scala:1233) ~[scala-library-2.11.7.jar:na]
	at scala.collection.immutable.Stream$Cons.tail(Stream.scala:1223) ~[scala-library-2.11.7.jar:na]
	at scala.collection.immutable.Stream$$anonfun$$plus$plus$1.apply(Stream.scala:372) ~[scala-library-2.11.7.jar:na]
	at scala.collection.immutable.Stream$$anonfun$$plus$plus$1.apply(Stream.scala:372) ~[scala-library-2.11.7.jar:na]
	at scala.collection.immutable.Stream$Cons.tail(Stream.scala:1233) ~[scala-library-2.11.7.jar:na]
	at scala.collection.immutable.Stream$Cons.tail(Stream.scala:1223) ~[scala-library-2.11.7.jar:na]
	at com.twitter.finagle.service.FailureAccrualFactory.markDead(FailureAccrualFactory.scala:268) ~[finagle-core_2.11-6.30.0.jar:6.30.0]
	at com.twitter.finagle.service.FailureAccrualFactory.com$twitter$finagle$service$FailureAccrualFactory$$didFail(FailureAccrualFactory.scala:249) ~[finagle-core_2.11-6.30.0.jar:6.30.0]
	at com.twitter.finagle.service.FailureAccrualFactory$$anonfun$apply$3.apply(FailureAccrualFactory.scala:319) ~[finagle-core_2.11-6.30.0.jar:6.30.0]
	at com.twitter.finagle.service.FailureAccrualFactory$$anonfun$apply$3.apply(FailureAccrualFactory.scala:319) ~[finagle-core_2.11-6.30.0.jar:6.30.0]
	at com.twitter.util.Future$$anonfun$onFailure$1.apply(Future.scala:988) ~[util-core_2.11-6.29.0.jar:6.29.0]
	at com.twitter.util.Future$$anonfun$onFailure$1.apply(Future.scala:987) ~[util-core_2.11-6.29.0.jar:6.29.0]
	at com.twitter.util.Promise$Monitored.apply(Promise.scala:73) [util-core_2.11-6.29.0.jar:6.29.0]
	at com.twitter.util.Promise$Monitored.apply(Promise.scala:64) [util-core_2.11-6.29.0.jar:6.29.0]
	at com.twitter.util.Promise$$anon$2.run(Promise.scala:358) [util-core_2.11-6.29.0.jar:6.29.0]
	at com.twitter.concurrent.LocalScheduler$Activation.run(Scheduler.scala:180) [util-core_2.11-6.29.0.jar:6.29.0]
	at com.twitter.concurrent.LocalScheduler$Activation.submit(Scheduler.scala:138) [util-core_2.11-6.29.0.jar:6.29.0]
	at com.twitter.concurrent.LocalScheduler.submit(Scheduler.scala:209) [util-core_2.11-6.29.0.jar:6.29.0]
	at com.twitter.concurrent.Scheduler$.submit(Scheduler.scala:93) [util-core_2.11-6.29.0.jar:6.29.0]
	at com.twitter.util.Promise.runq(Promise.scala:342) [util-core_2.11-6.29.0.jar:6.29.0]
	at com.twitter.util.Promise.updateIfEmpty(Promise.scala:718) [util-core_2.11-6.29.0.jar:6.29.0]
	at com.twitter.util.Future$$anonfun$3.apply$mcV$sp(Future.scala:841) [util-core_2.11-6.29.0.jar:6.29.0]
	at com.twitter.util.Monitor$.apply(Monitor.scala:128) [util-core_2.11-6.29.0.jar:6.29.0]
	at com.twitter.finagle.util.HashedWheelTimer.com$twitter$finagle$util$HashedWheelTimer$$runInContext(HashedWheelTimer.scala:50) [finagle-core_2.11-6.30.0.jar:6.30.0]
	at com.twitter.finagle.util.HashedWheelTimer$$anon$3.run(HashedWheelTimer.scala:16) [finagle-core_2.11-6.30.0.jar:6.30.0]
	at org.jboss.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:556) [netty-3.10.1.Final.jar:na]
	at org.jboss.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:632) [netty-3.10.1.Final.jar:na]
	at org.jboss.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:369) [netty-3.10.1.Final.jar:na]
	at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108) [netty-3.10.1.Final.jar:na]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_65]`

### Steps to reproduce the behavior

I am trying to locate more precise what is causing this so I can create a little app that reproduces this because I can not give out the source of the app I am working with.

**Comment by jcrossley** [comment]
Hi Oscar! I recall this issue, and it was fixed in a more recent Finagle. I see you're on 6.30; can you update to the latest, 6.45? https://github.com/twitter/finagle/tree/finagle-6.45.0

**Comment by codeape** [comment]
Thank you. I will get back to you as soon as I have tested your solution. Hopefully on Monday :)

**Comment by vkostyukov** [comment]
Closing this as it's not a problem on the most recent Finagle. @codeape Feel free to reopen should you reproduce it on Finagle 7.
