### ISSUE TITLE
Finagle Client raised NullPointerException when Loading Client Stats receiver

### ISSUE THREAD

**Issue by MohsinBXL** [twitter/finagle#695]
I have an issue by running my application on Websphere and starting connecting the service discovery via Finagle transitive libraries 

### Expected behavior
Connecting to a service Discovery via Finagle http client through client stats receiver

### Actual behavior

The Web App failed to load because of NullpointerException on Finagle lib dependencies. Regarding the stack trace, It is looking for something in the classpath.

Caused by: java.lang.NullPointerException
    at scala.collection.mutable.ArrayOps$ofRef$.length$extension(ArrayOps.scala:200)
    at scala.collection.mutable.ArrayOps$ofRef.length(ArrayOps.scala:200)
    at scala.collection.IndexedSeqOptimized.foreach(IndexedSeqOptimized.scala:31)
    at scala.collection.IndexedSeqOptimized.foreach$(IndexedSeqOptimized.scala:29)
    at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:194)
    at com.twitter.app.ClassPath.getEntries(ClassPath.scala:72)
    at com.twitter.app.ClassPath.getEntries(ClassPath.scala:68)
    at com.twitter.app.ClassPath.getEntries(ClassPath.scala:68)
    at com.twitter.app.ClassPath.getEntries(ClassPath.scala:68)
    at com.twitter.app.ClassPath.getEntries(ClassPath.scala:68)
    at com.twitter.app.ClassPath.browse(ClassPath.scala:57)
    at com.twitter.app.LoadService$$anon$1.apply(LoadService.scala:40)
    at com.twitter.app.LoadService$$anon$1.apply(LoadService.scala:38)
    at java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1671)
    at com.twitter.app.LoadService$.apply(LoadService.scala:45)
    at com.twitter.finagle.util.LoadService$.apply(LoadService.scala:14)
    at com.twitter.finagle.stats.LoadedStatsReceiver$.<init>(LoadedStatsReceiver.scala:18)
    at com.twitter.finagle.stats.LoadedStatsReceiver$.<clinit>(LoadedStatsReceiver.scala)
    ... 90 more

**Comment by cacoco** [comment]
@MohsinBXL thanks for the issue, we'll take a look. It looks that perhaps the URLClassloader can return nulls in the array and it isn't being properly handled. We'll take a look, thanks!

**Comment by cacoco** [comment]
Fix merged in Util: https://github.com/twitter/util/commit/3adca94a9e2b21a702aad619902ce5ef2e29de65
