### ISSUE TITLE
com.twitter.finagle.ServiceClosedException: null during updating Var

### ISSUE THREAD

**Issue by DanielCharczynski** [twitter/finagle#814]
ServiceClosedException during updatig Var

### Expected behavior

I'm no sure if it is proper behavior that something is closed during updating Var

### Actual behavior

```
com.twitter.finagle.ServiceClosedException: null
      at com.twitter.finagle.pool.WatermarkPool.$anonfun$close$1(WatermarkPool.scala:228)
      at com.twitter.finagle.pool.WatermarkPool.$anonfun$close$1$adapted(WatermarkPool.scala:227)
      at com.twitter.finagle.pool.WatermarkPool$$Lambda$1331.000000009A2C22F0.apply(Unknown Source)
      at scala.collection.IndexedSeqOptimized.foreach(IndexedSeqOptimized.scala:32)
      at scala.collection.IndexedSeqOptimized.foreach$(IndexedSeqOptimized.scala:29)
      at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:194)
      at com.twitter.finagle.pool.WatermarkPool.close(WatermarkPool.scala:227)
      at com.twitter.finagle.ServiceFactoryProxy.close(ServiceFactoryProxy.scala:16)
      at com.twitter.finagle.ServiceFactoryProxy.close(ServiceFactoryProxy.scala:16)
      at com.twitter.finagle.liveness.FailureAccrualFactory.close(FailureAccrualFactory.scala:455)
      at com.twitter.finagle.ServiceFactoryProxy.close(ServiceFactoryProxy.scala:16)
      at com.twitter.finagle.ServiceFactoryProxy.close(ServiceFactoryProxy.scala:16)
      at com.twitter.finagle.ServiceFactoryProxy.close(ServiceFactoryProxy.scala:16)
      at com.twitter.finagle.ServiceFactoryProxy.close(ServiceFactoryProxy.scala:16)
      at com.twitter.finagle.ServiceFactoryProxy.close(ServiceFactoryProxy.scala:16)
      at com.twitter.finagle.ServiceFactoryProxy.close(ServiceFactoryProxy.scala:16)
      at com.twitter.finagle.ServiceFactoryProxy.close(ServiceFactoryProxy.scala:16)
      at com.twitter.finagle.Filter$$anon$2.close(Filter.scala:121)
      at com.twitter.finagle.ServiceFactoryProxy.close(ServiceFactoryProxy.scala:16)
      at com.twitter.finagle.ServiceFactoryProxy.close(ServiceFactoryProxy.scala:16)
      at com.twitter.finagle.ServiceFactoryProxy.close(ServiceFactoryProxy.scala:16)
      at com.twitter.finagle.Filter$$anon$2.close(Filter.scala:121)
      at com.twitter.finagle.ServiceFactoryProxy.close(ServiceFactoryProxy.scala:16)
      at com.twitter.finagle.loadbalancer.LazyEndpointFactory.close(EndpointFactory.scala:146)
      at com.twitter.util.Closable.close(Closable.scala:21)
      at com.twitter.util.Closable.close$(Closable.scala:21)
      at com.twitter.finagle.ServiceFactory.close(ServiceFactory.scala:5)
      at com.twitter.finagle.loadbalancer.TrafficDistributor.$anonfun$weightEndpoints$6(TrafficDistributor.scala:187)
      at com.twitter.finagle.loadbalancer.TrafficDistributor$$Lambda$674.00000000950C1410.apply(Unknown Source)
      at scala.collection.TraversableOnce.$anonfun$foldLeft$1(TraversableOnce.scala:157)
      at scala.collection.TraversableOnce.$anonfun$foldLeft$1$adapted(TraversableOnce.scala:157)
      at scala.collection.TraversableOnce$$Lambda$156.00000000946CBAF0.apply(Unknown Source)
      at scala.collection.immutable.Set$Set1.foreach(Set.scala:95)
      at scala.collection.TraversableOnce.foldLeft(TraversableOnce.scala:157)
      at scala.collection.TraversableOnce.foldLeft$(TraversableOnce.scala:155)
      at scala.collection.AbstractTraversable.foldLeft(Traversable.scala:104)
      at com.twitter.finagle.loadbalancer.TrafficDistributor.$anonfun$weightEndpoints$1(TrafficDistributor.scala:183)
      at com.twitter.finagle.loadbalancer.TrafficDistributor$$Lambda$655.0000000095069FB0.apply(Unknown Source)
      at com.twitter.finagle.loadbalancer.TrafficDistributor$.$anonfun$safelyScanLeft$1(TrafficDistributor.scala:68)
      at com.twitter.finagle.loadbalancer.TrafficDistributor$$$Lambda$656.000000009506A6D0.apply(Unknown Source)
      at com.twitter.util.Event$$anon$3.$anonfun$register$3(Event.scala:118)
      at com.twitter.util.Event$$anon$3.$anonfun$register$3$adapted(Event.scala:117)
      at com.twitter.util.Event$$anon$3$$Lambda$666.000000009506F7B0.apply(Unknown Source)
      at com.twitter.util.Function$.$anonfun$synchronizeWith$1(Function.scala:41)
      at com.twitter.util.Function$$$Lambda$667.00000000950706D0.apply(Unknown Source)
      at com.twitter.util.Witness$$anon$17.notify(Event.scala:499)
      at com.twitter.util.Var$$anon$3.$anonfun$register$1(Var.scala:135)
      at com.twitter.util.Var$$anon$3.$anonfun$register$1$adapted(Var.scala:134)
      at com.twitter.util.Var$$anon$3$$Lambda$624.0000000095012510.apply(Unknown Source)
      at com.twitter.util.Var$Observer.publish(Var.scala:189)
      at com.twitter.util.Var$Value.observe(Var.scala:265)
      at com.twitter.util.Var$$anon$2.$anonfun$observe$1(Var.scala:113)
      at com.twitter.util.Var$$anon$2.$anonfun$observe$1$adapted(Var.scala:101)
      at com.twitter.util.Var$$anon$2$$Lambda$668.00000000950BE7F0.apply(Unknown Source)
      at com.twitter.util.Var$Observer.publish(Var.scala:189)
      at com.twitter.util.UpdatableVar.$anonfun$update$3(Var.scala:512)
      at com.twitter.util.UpdatableVar.$anonfun$update$3$adapted(Var.scala:507)
      at com.twitter.util.UpdatableVar$$Lambda$606.0000000094FDC990.apply(Unknown Source)
      at scala.collection.TraversableLike$WithFilter.$anonfun$foreach$1(TraversableLike.scala:789)
      at scala.collection.TraversableLike$WithFilter$$Lambda$226.00000000948C0EF0.apply(Unknown Source)
      at scala.collection.immutable.RedBlackTree$._foreachKey(RedBlackTree.scala:109)
      at scala.collection.immutable.RedBlackTree$.foreachKey(RedBlackTree.scala:105)
      at scala.collection.immutable.TreeSet.foreach(TreeSet.scala:153)
      at scala.collection.TraversableLike$WithFilter.foreach(TraversableLike.scala:788)
      at com.twitter.util.UpdatableVar.update(Var.scala:507)

```

### Steps to reproduce the behavior

It might be hard to reproduce because it might happens during high workload

**Comment by mosesn** [comment]
@DanielCharczynski not sure how to help you here, if you (or anyone else) comes up with a cleaner reproduction case, we're happy to dig deeper!  Or if you're able to figure out what's going on from reading the code, we're happy to provide further guidance.

**Comment by enbnt** [comment]
Re-ping to see if we should leave this open or close out shortly?
